// <auto-generated />
using System;
using LagerSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LagerSystem.Migrations
{
    [DbContext(typeof(LagerSystemContext))]
    partial class LagerSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LagerSystem.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "FOOD",
                            Count = 100,
                            Description = "",
                            Name = "SWEETS",
                            Orderdate = new DateTime(1995, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30,
                            Shelf = "2"
                        },
                        new
                        {
                            Id = 2,
                            Category = "SHOPPING",
                            Count = 100,
                            Description = "",
                            Name = "T-SHIRT",
                            Orderdate = new DateTime(1995, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30,
                            Shelf = "2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "SHOPPING",
                            Count = 100,
                            Description = "",
                            Name = "TROUSER",
                            Orderdate = new DateTime(1995, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30,
                            Shelf = "2"
                        },
                        new
                        {
                            Id = 4,
                            Category = "FOOD",
                            Count = 100,
                            Description = "",
                            Name = "MEAT",
                            Orderdate = new DateTime(1995, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30,
                            Shelf = "2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
